### PR TITLE
Added scripts to package and deploy the legacy SageTV UIs

### PR DESCRIPTION
**Pull request by stuckless**
so they can be installed as a SageTV 9 plugin

### CODE REVIEW

**Comment by Narflex** [comment]
Pardon my ignorance, but how does this actually work and get those STVs into the plugin repo?

**Comment by stuckless** [comment]
The README.md basically explains what is happening...

> The build.xml script will package any stv defined in the stvs folder and create a valid SageTV 9 STV package for it.
> 
> # ant -Dstv.name=SageTV3
> Will create the SageTV3-9.0.zip theme package and xml in the pluginrelease folder.
> 
> To upload the theme package to BinTray you can use the plugin-uploader.gradle script in the root of the project.
> 
> # ./gradlew -b plugin-uploader.gradle -Dstv.name=SageTV3 bintrayUpload
> These legacy SageTV UIs are not expected to change, so they are not a part of the standard build/deployment process.
> 
> 

So, this is really about the scripts necessary to create these packages and uploading them to BinTray... This is not a part of the full build process, since, this is not something that is likely to change, ever.  ie, we are not supporting enhancing these, we are just making them available.

The process to get them into the SageTV9 repo is basically commit their plugin manifests to the SageTV9 repo (which is done).

So, this builds the packages and uploads to bintray... manual process.  And it's a manual process to update the plugin repository with the manifest... There isn't really a need to automate this with the build, since, this will likely not happen often.

**Comment by stuckless** [comment]
Here's link to the SageTV9 plugin repo.

https://github.com/OpenSageTV/sagetv-plugin-repo

The manifests are in the plugins/sagetv/ area

https://github.com/OpenSageTV/sagetv-plugin-repo/tree/master/plugins/sagetv

**Comment by Narflex** [comment]
Ok, gotcha. You used these tools when doing it yourself and just wanted to
have them in the repo. Makes sense.

Jeff Kardatzke

**Pull request merged**
