### PR TITLE
Allow all valid characters in filename

### PR DESCRIPTION
**Pull request by atarijeff**
Keep all legal filename characters in show and episode names. Added spaces around '-' delimiters in name string to allow 3rd party metadata scrapers to read SageTV recordings.

### CODE REVIEW

**Comment by Narflex** [comment]
Please take a look at the CONTRIBUTING file and sign the Google CLA, then I can accept code from you (I'll also look over it now and let you know if there's any other issues).

**Comment by Narflex** [comment]
Please fix the indentation in your commit. I do realize not all of the SageTV code is properly indented currently...but I'd like new code to be. We are following the convention of 2 spaces per indent and use spaces instead of tabs.

**Comment by Narflex** [comment]
Otherwise I'm fine with this change and will approve it once you sign the CLA and fix the indentation. :)

**Comment by atarijeff** [comment]
I have signed the CLA and updated the indents as requested. Let me know if there's anything else you need.

Jeff

**Pull request merged**
