### PR TITLE
Refactored GSON 2.7 for Schedules Direct

### PR DESCRIPTION
**Pull request by enternoescape**

### CODE REVIEW

**Comment by Narflex** [comment]
I just need to check with some folks internally to see if this needs to go in the third_party directory or not since it is Google code, but from a different project.

**Comment by enternoescape** [comment]
I can just move it and save you the effort. It might make it easier to understand what's going on down the road too.

**Comment by Narflex** [comment]
I already asked....your call, I'll get a response but it might not be until
Monday.

Jeff Kardatzke

**Comment by enternoescape** [comment]
I moved it. Let me know if you need further details in the folder or what other files need to be updated for legal reasons.

**Comment by CraziFuzzy** [comment]
So will we also need to alter the plugin repo to remove the gson.jar with this change? (I'm reading this as pulling GSON into the core, right?)

**Comment by enternoescape** [comment]
It's refactored into another package, so it will not conflict with GSON if someone else imports a different version of GSON for a plugin.

**Comment by CraziFuzzy** [comment]
Got ya.. if I had thought for more than a couple seconds on it I would have realized that.. ;-)

**Pull request merged**
