### PR TITLE
Release for version 9.1.10 [ci release]

### PR DESCRIPTION
**Pull request by jusjoken**

### CODE REVIEW

**Comment by jusjoken** [comment]
Please hold on this PR for now as we are having issues with BinTray which we should resolve before this auto builds a new Linux version

**Comment by Narflex** [comment]
OK, let me know when you want it merged. But shouldn't those 2 other changed files in this PR also have the micro version incremented? (looks like they are autogenerated)

**Comment by jusjoken** [comment]
I missed a commit after the script had run.  So I have added these to this PR.  But please hold on this until the Bintray issue is resolved

**Comment by jusjoken** [comment]
Bintray is working again so feel free to merge this if you are ok with it

**Pull request merged**
