### PR TITLE
Release for version 9.2.4 [ci release]

### PR DESCRIPTION
**Pull request by wnjj**
Modified Windows installer to source Java from Github instead of Bintray.  Added "ci release" to build Linux version.

### CODE REVIEW

**Comment by wnjj** [comment]
Looks like Travis CI is no longer running?  Also, a Linux guy will need to get the auto-upload changed to Github/OpenSageTV instead of Bintray.

**Comment by Narflex** [comment]
> Looks like Travis CI is no longer running? Also, a Linux guy will need to get the auto-upload changed to Github/OpenSageTV instead of Bintray.

I noticed you disabled the uploading in the change...but that's in the Windows installer (but you mentioned Linux). What's actually broken in it?

**Comment by wnjj** [comment]
> > Looks like Travis CI is no longer running? Also, a Linux guy will need to get the auto-upload changed to Github/OpenSageTV instead of Bintray.
> 
> I noticed you disabled the uploading in the change...but that's in the Windows installer (but you mentioned Linux). What's actually broken in it?

Bintray is going away next month.  The Linux builds would auto upload to Bintray using Travis-ci though it doesn’t seem to be running at the moment anyway.  I manually uploaded the Windows installers to the OpenSageTV GitHub site since the upload automation isn’t built yet.  I don’t have any way to build the Linux packages.  For the previous Linux release, I downloaded them from Bintray and uploaded the them to GitHub manually.

Ideally we talk Stuckless or someone else into fixing the upload script to upload to GitHub directly.

**Comment by Narflex** [comment]
OK, well hopefully somebody will fix that....but I won't block this because of that.

**Pull request merged**
