### PR TITLE
Use non-legacy v4l-dvb API for tuning DVB-S2/PSK_8

### PR DESCRIPTION
**Pull request by rflitcroft**
Use non-legacy v4l-dvb API for tuning DVB-S2/PSK_8
Fix crash when scanning DVB-S channels

### CODE REVIEW

**Comment by Narflex** [comment]
Can you explain more what these specific changes accomplish? I'm not that familiar with this code and I want to understand better if this will break anything for other usages of it or not. If there's a forum thread about it...please point me there too. :)

Also, please look at the CONTRIBUTING file, you need to sign the Google CLA in order to contribute code to this project.

**Comment by rflitcroft** [comment]
Hi Narflex -
The v4l API used in sage_DVBCaptureDevice.c used the legacy method of tuning DVB cards via the FE_SET_FRONTEND function call. This function only supports DVB-S/C/T and not DVB-S2/T2, for which the newer FE_SET_PROPERTY function must be used. [http://linuxtv.org/downloads/v4l-dvb-apis/frontend_legacy_dvbv3_api.html]
The changes to sage_DVBCaptureDevice.c use the newer function calls for tuning DVB-S(2) cards. (A similar change could be used to enable DVB-T2 cards).

I guess there is a risk on really old linux systems which do not support the newer API functions, but they are not new any more. I did have a look at the libdvbv5 library which abstracts the API calls quite nicely and auto-detects when to use the legacy functions, but that seemed like a lot of work and a major refactor.

The change to Channel.c enabled a DVB-S scan to proceed without a seg fault.

I will open a new thread on the forums to try to invite some more wisdom from the community.

Rich

**Comment by rflitcroft** [comment]
Discussion thread here: [http://forums.sagetv.com/forums/showthread.php?p=587425#post587425]!

**Comment by Narflex** [comment]
Thanks for the update...all the changes make sense then. Just 2 favors before I merge it. You need to sign the Google CLA as I mentioned; and then also if you could get at least one other person to test this (and if nobody responds to your forum post about it in a timely fashion, then I'll just merge it anyways).

Now I see the forums post too...just ping me again on this when somebody else tests it, or if a week goes by and nobody responds, ping me again and I'll just go ahead and merge it. Thanks for the contribution!

**Comment by rflitcroft** [comment]
The CLA's have been signed - did them with my previous pull request. 
I'll let you know if get any bites on the forum...
R

**Comment by Narflex** [comment]
When I look up the CLA it's not indicating you've signed it (and it's very fast at updating). Are you sure you attached it to this GitHub user name?

**Comment by rflitcroft** [comment]
OK - Looks like the CLA was using to my email address and not my GitHub username. I've updated the CLA accordingly. Sorry about that.

**Comment by Narflex** [comment]
No problem, I checked and now you are verified. :)

On Tue, Apr 12, 2016 at 3:23 PM, Richard Flitcroft <notifications@github.com
> wrote:

> OK - Looks like the CLA was using to my email address and not my GitHub
> username. I've updated the CLA accordingly. Sorry about that.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/pull/125#issuecomment-209127460>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by Narflex** [comment]
Did you get any more feedback on this or find any problems? If no issues were found, let me know and I'll merge this now.

**Comment by rflitcroft** [comment]
No feedback sadly. I'm confident about the v4l api changes, but less so about the change to ax/Channel-2/Channel.c which I assume is shared across Windows and Linux. It did prevent a crash in Linux, but I think the root cause of the crash is in sage_DVBCaptureDevice.c. However it's simple enough to revert that - the original code is just commented out.
To be on the safe side, I'll revert the change to Channel.c and then I'm as happy with it as I can be. 
I would rather keep the pull requests confined to specific problems rather than try to fix too much in a single commit.

**Comment by rflitcroft** [comment]
Revert unverified change to scanDVBSChannel.c

**Pull request merged**
