### PR TITLE
A missing space in an if test prevents the Linux SageTV start script from running.

### PR DESCRIPTION
**Pull request by enternoescape**
Let's all agree to leave well enough alone on this one. It's working. We shall not change this piece of code ever again. :)

### CODE REVIEW

**Comment by CraziFuzzy** [comment]
HA!.. picked a hell of a time to update unRAID, only to have the wife complain an hour later "The client's not seeing the server!"  Sure enough, it wasn't running.. ;-)

**Comment by CraziFuzzy** [comment]
Still feel we need to somehow get the updates to come via docker container updates, not restarting the container.  Would prevent unintended updates like this causing mass problems, because it would take deliberate user intervention to update sagetv.

**Comment by enternoescape** [comment]
That's easy. We would just hard code the SageTV version into the container. Then the container would need to be updated any time a new version was released. That would mean more work for @stuckless since he would then need to either automate the version incrementing of his containers or update them manually with each release.

**Comment by enternoescape** [comment]
It does look like Travis CI is having some performance issues with our specific build type. They have some messages from 5/30 indicating that they are working with Google to sort out what's going wrong.

**Comment by CraziFuzzy** [comment]
Yeah, hard coding the version into the script would be possible I suppose - would be a lot easier if the docker stuff was integrated into the gradle build, I'm guessing.  Part of a bigger job I suppose, since we need to see how to get the windows builds going as well.

**Comment by enternoescape** [comment]
That's mostly what I meant by automating the hard coding. Something could be added to the Gradle script that would also update the Docker container so people know a newer version of SageTV is available. The problem SageTV has is that the software binary is mostly external to the container because the configuration is mixed in and because of the way it's written out, hard links wouldn't get the job done.

Alternatively there could a script to update the Docker container repo that when run checks if there's a newer version of SageTV and if so it pushes an update to the repo to use the new version. The "current" version could just be stored in a file that's checked on startup and that would make it very easy to update at the repo level by script. This approach would be more modular and not require any changes on the SageTV build side of things.

**Comment by enternoescape** [comment]
For the record, I fully support what you're suggesting. I like the automatic upgrades, but I also can see why some people might be caught off-guard by them. We have a property that lets you go between versions easily, but some kind of prompt that you will be upgrading to a new version would likely be very helpful to most people.

**Comment by CraziFuzzy** [comment]
I'm really wondering though just how hard it would be to switch the sagetv home folder separate from the binaries.  Just about all the files in question are generated on first runtime (wiz.bin, SageTV.properties, etc).  Might be worth an issue to track that improvement, even if it's just breaking apart some path variables at this point.  We shouldn't hold to legacy forever, if we have the option to move away from it.

**Comment by enternoescape** [comment]
We had this discussion in the forums. I would be willing to put in the work if I didn't think it would break a lot of plugins along the way. You saw what happened when we just changed a classpath. This kind of change would require a shift in how plugin developers store persistent data. We might need to somehow shim the legacy plugins so they use the right locations and have some new requirements for new/updated plugins. The STV's would also need to be moved around which would likely cause it's own huge problem. I'm just not sure it's reasonable to attempt this.

I've been contemplating a plugin 2.0 system that provides the plugins with a folder they can do what they will with to ensure they place persistent data in a safe location that no other plugin will try to disturb. I was also thinking about ways to isolate plugins from the main JVM so that they can be accessed via the STV and they have full access to the main JVM through the API, but not introduce new dependencies to it or conflict with other plugin requirements. This would of course be through some kind of native bridge or local network connection and the plugins would likely run in their own JVM's. This would also keep any plugin from hosing the core program and might even make plugin development easier since you could then in theory run your plugin in the IDE with SageTV using it like it was installed the traditional way.

**Comment by CraziFuzzy** [comment]
Like I said, it probably should have it's own issue topic so we can continue the discussion, because i do think it should be a long term goal.  I do have some ideas on how to deal with it, and some groundwork is already in the core to deal with it (the Sage.getPath function).  There are things in the core, however, that do not use this, and instead use System.getProperty("user.dir") instead that would need to be changed.  I'm sure there are plenty of plugins that also use user.dir.  The issue with the plugins COULD be handled by launching from the data directory, making that the "user.dir" as far as java is concerned, then any plugins that are using user.dir would be homed there, and newer/proper plugins would be geting the correct path from Sage.getPath.

**Comment by enternoescape** [comment]
I missed where you said this should be it's own topic, but I agree. I can see how this could be in incremental moving forward goal.

**Pull request merged**
