### PR TITLE
Build for 9.2.1 [ci release] - first release of Windows x64 installers

### PR DESCRIPTION
**Pull request by jusjoken**
- Windows installer changes
- minor build.gradle change to build sage.jar on windows
- skipped 9.2.0 as many users are using that beta release and moving to 9.2.1 will allow them to upgrade

### CODE REVIEW

**Comment by wnjj** [comment]
You may want to add the 64-bit Windows AVI playback and music fixes to the changelog.

**Comment by wnjj** [comment]
Unless those fixes were considered beta anyway and this is the first official full release.  Just thinking of those running 9.2.0 now and documenting the difference.

**Comment by jusjoken** [comment]
Done

**Comment by Narflex** [comment]
Thanks!

**Pull request merged**
